### PR TITLE
preg split returned na array with no values.

### PR DESCRIPTION
**Pull request by HellPat**
preg split returned na array with no values.
preg_match fixed the problem. Is this due misconfiguration?

Why is a limit here?

Seems to work for me now, but you know better why you did that.
(I cant with my limited php knowledge)

### CODE REVIEW

**Comment by stefanheimes** [comment]
Hi, 

this is a good question. I don't know what the best way is.
Here is a little Example, how it works for us:

## Configuration:

Target

```
Url: be-nl
regular expression: true
```

Redirect settings

```
Targettype: External redirect
Redirecttype: 301/307
URL: nl$1
```

## Result:

http://my-domain.de/be-nl/start.html => http://my-domain.de/nl/start.html
http://my-domain.de/be-nl/my/page/start.html => http://my-domain.de/nl/my/page/start.html

**Comment by HellPat** [comment]
preg_split didn't work for me. Can you test if it works as expected with preg_match.
I'm a bit confused with the limit of 2.

Now it works for me.

## Configuration:

```
URL: (be)-(.*)
Regexp: true
Redirect Url: $2
Countries (why plural?): be
```

## Result:

```
/be-nl/start.html => /nl/start.html
/be-en/start.html => /en/start.html
```

So i'm fine with this solution.

**Comment by stefanheimes** [comment]
Ah okay. Yeah this seems to be a better way, i think we change this. 

About the "Countries". It is possible to add more than one country to geolocation, so we add a checkboxwizard and called it "Countries".

**Comment by HellPat** [comment]
which usecase does multiple coutries have? I tried but the user is located in the first country which was selected (or am i wrong)?!

**Comment by HellPat** [comment]
Sorry for my noobish branch cluttering.

**Comment by stefanheimes** [comment]
Ready for merge ?

**Comment by HellPat** [comment]
Yes, ready for merge. I removed the stupid parts.

**Pull request merged**
